main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Uxzylon
description: Place Custom Model Data Easily
commands:
  model3d:
    description: Place Custom Model Data Easily
    usage: /<command> <fonction>
    permission: custommodeltools.command
permissions:
  custommodeltools.command.give:
    description: Allow give command
    default: op
    children:
      custommodeltools.command: true
  custommodeltools.command.move:
    description: Allow move command
    default: op
    children:
      custommodeltools.command: true
  custommodeltools.command.place:
    description: Allow place command
    default: op
    children:
      custommodeltools.command: true
  custommodeltools.command.remove:
    description: Allow remove command
    default: op
    children:
      custommodeltools.command: true
  custommodeltools.command.select:
    description: Allow select command
    default: op
    children:
      custommodeltools.command: true
  custommodeltools.command.unselect:
    description: Allow unselect command
    default: op
    children:
      custommodeltools.command: true
  custommodeltools.command.switch:
    description: Allow switch command
    default: op
    children:
      custommodeltools.command: true
  custommodeltools.command.reload:
    description: Allow reload command
    default: op
    children:
      custommodeltools.command: true
  custommodeltools.bypass.resourcepack:
    description: Allow bypass resourcepack
    default: false
    children:
      custommodeltools.bypass: true
  custommodeltools.*:
    description: Grants all other permissions
    default: false
    children:
      custommodeltools.command: true
      custommodeltools.bypass: true
  custommodeltools.command.*:
    description: Grants all permissions for commands
    default: false
    children:
      custommodeltools.command.give: true
      custommodeltools.command.move: true
      custommodeltools.command.place: true
      custommodeltools.command.remove: true
      custommodeltools.command.select: true
      custommodeltools.command.unselect: true
      custommodeltools.command.switch: true
      custommodeltools.command.reload: true
  custommodeltools.bypass.*:
    description: Grants all permissions for bypass
    default: false
    children:
      custommodeltools.bypass.resourcepack: true