main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Uxzylon
description: Place Custom Model Data Easily
commands:
  model3d:
    description: Place Custom Model Data Easily
    usage: /<command> <fonction>
    permission: model3dplacer.command
permissions:
  model3dplacer.command.give:
    description: Allow give command
    default: op
    children:
      model3dplacer.command: true
  model3dplacer.command.move:
    description: Allow move command
    default: op
    children:
      model3dplacer.command: true
  model3dplacer.command.place:
    description: Allow place command
    default: op
    children:
      model3dplacer.command: true
  model3dplacer.command.remove:
    description: Allow remove command
    default: op
    children:
      model3dplacer.command: true
  model3dplacer.command.select:
    description: Allow select command
    default: op
    children:
      model3dplacer.command: true
  model3dplacer.command.unselect:
    description: Allow unselect command
    default: op
    children:
      model3dplacer.command: true
  model3dplacer.command.switch:
    description: Allow switch command
    default: op
    children:
      model3dplacer.command: true
  model3dplacer.*:
    description: Grants all other permissions
    default: false
    children:
      model3dplacer.command: true